AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-dynamo

  Sample SAM Template for lambda-dynamo
  
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorldGet:
          Type: Api 
          Properties:
            Path: /hello
            Method: get
        HelloWorldPost:
          Type: Api 
          Properties:
            Path: /hello
            Method: post
        HelloWorldDelete:
          Type: Api 
          Properties:
            Path: /hello
            Method: delete
        HelloWorldUpdate:
          Type: Api 
          Properties:
            Path: /hello
            Method: put
        CategoriaGet:
          Type: Api 
          Properties:
            Path: /categoria
            Method: get
        CategoriaScan:
          Type: Api 
          Properties:
            Path: /categoriaScan
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
